---
OrdererOrgs:
  - Name: foodtrace.com
    Domain: foodtrace.com
    Specs:
      - Hostname: orderer1
        SANS:
          - 101.43.206.180
      - Hostname: orderer2
        SANS:
          - 101.43.206.180
      - Hostname: orderer3
        SANS:
          - 101.43.206.180

PeerOrgs:
  - Name: org0.foodtrace.com
    Domain: org0.foodtrace.com
    EnableNodeOUs: true
    CA:
      Hostname: ca1
      CommonName: ca1.org0.foodtrace.com
      Country: US
      Province: North Carolina
      Locality: Raleigh
    Specs:
      - Hostname: peer1
        CommonName: peer1.org0.foodtrace.com
        SANS:
          - 101.43.206.180
      - Hostname: peer2
        CommonName: peer2.org0.foodtrace.com
        SANS:
          - 101.43.206.180
  - Name: org1.foodtrace.com
    Domain: org1.foodtrace.com
    EnableNodeOUs: true
    CA:
      Hostname: ca1
      CommonName: ca1.org1.foodtrace.com
      Country: US
      Province: North Carolina
      Locality: Raleigh
    Specs:
      - Hostname: peer1
        CommonName: peer1.org1.foodtrace.com
        SANS:
          - 101.43.206.180
      - Hostname: peer2
        CommonName: peer2.org1.foodtrace.com
        SANS:
          - 101.43.206.180
  - Name: org2.foodtrace.com
    Domain: org2.foodtrace.com
    EnableNodeOUs: true
    CA:
      Hostname: ca1
      CommonName: ca1.org2.foodtrace.com
      Country: US
      Province: North Carolina
      Locality: Raleigh
    Specs:
      - Hostname: peer1
        CommonName: peer1.org2.foodtrace.com
        SANS:
          - 101.43.206.180
      - Hostname: peer2
        CommonName: peer2.org2.foodtrace.com
        SANS:
          - 101.43.206.180
